### ISSUE TITLE
artefacts introduced by rotate to coverslip

### ISSUE THREAD

**Issue by VolkerH** [VolkerH/Lattice_Lightsheet_Deskew_Deconv#22]
noticed that rotate to coverslip introduces some "stripy" artefacts (similar to interlacing). 
(even when not deconvolving). 
Not sure whether this is an artefact of the volume renderer or is actually in the data.
(most likely cause would be an error in resampling)

**Comment by VolkerH** [comment]
![image](https://user-images.githubusercontent.com/2210044/54888030-a42ae100-4eed-11e9-94bc-c3059f8c7adf.png)

Left shows a volume that has been deskewed and rotated to coverslip coordinates with a single affine transform.

Right shows the volume having been deskewed, scaled and then rotated to coverslip with three seperate affine transforms. 

Initial thoughts were that this was due to low order of interpolation or incorrect implementation of affine transformation in gputools. After trying different implementations (including the one in TransformJ in Fiji) and orders of interpolation it turned out not to be the case. 

I assume this has to do with undersampling (the spacing of voxels along the diagonal is sqrt(3) larger, which can lead to undersampling of structures when they are rotated) that introduces aliasing artefacts. There is some inherent low-pass filtering happening with each interpolation and it appears that interpolating at each step (deskew, z-scaling, rotation) sufficiently band-limits the signal to avoid these aliasing-effects. 
This is useful to understand what is happening (context is texture mapping) https://www.microsoft.com/en-us/research/wp-content/uploads/2010/02/MSR-TR-2010-10c.pdf
They break up a shearing transform into three steps for optimum quality. This should probably be done at the deskew step as well.

**Comment by dmilkie** [comment]
Is the problem that the left image is cropped/zoomed in? Or the interpolation is smoothing the right image more (since you are interpolating three separate times)?

-Dan

**Comment by VolkerH** [comment]
It is also visible at the same zoom level. I just didn't pay attentian when taking the screenshot.
Yes I think it has to do with more smoothing caused by three seperate interpolation steps which causes bandlimiting.

My current understanding of the problem: even if I had isotropic pixels, any rotation can introduce an undersampling as the diagonals in my voxel space are a factor of sqrt(3) wider spaced than the direct neighbours. Therefore, I would have to low-pass filter before applying the affine transform. I believe the tri-linear interpolation introduces some degree of low-pass filtering, but not necessarily the right amount. By interpolating at each step I probably get closer to the correct band-limiting. 

The counter-intuitive step here is that more interpolation steps actually lead to a better result. 
Another take-away message is that the deskew  should probably also be broken up into seperate steps (see Figure 4 of the technical report linked to above).

**Comment by VolkerH** [comment]
![image](https://user-images.githubusercontent.com/2210044/54888853-1521c700-4ef5-11e9-914a-a85de7318586.png)

Here another screenshot at 100% zoom and with same brightness contrast settings on both. The z-slices are more or less similarly chosen (the right volume has a lot of empty fill slices). 
The artefacts become even more obvious when moving through z with the slider.

**Comment by VolkerH** [comment]
The worst culprit is probably combining the Z-scaling operation with any of the other operations.

(edit: removed example that wasn't quite correct)

Mixing scaling in Z and rotation interpolates between voxels that have different physical spacings. The interpolation does not know about these (only aware of pixel distances) and thus weights the voxel distances equally where the x/y spacings should have much higher weight (as they are closer together). 

Performing the Z-scaling in a seperate step only causes interpolation along the Z-axis. For the subsequent steps the weights for the interpolation will then be correct.

**Comment by VolkerH** [comment]
Implemented the multi-step affine transformation in the main code. Based on initial testing the large artifacts from interpolating between non-isotropic pixels are gone. 
Having looked at this in detail I am convinved that I am also introducing some minor aliasing by shearing and rotation. I will not follow up on this immediately though, probably very diminishing returns.  
Closing this issue for now.
